language: android

before_install:
  - ./travis_prebuild.sh;

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25

    - extra-android-support

jdk: oraclejdk8

deploy:
  provider: script
  script: gradle core/publish-settings.gradle clean bintrayUpload
  skip_cleanup: true
  on:
    tags: true